name: 'Hetzner Cloud Action'
description: 'This action creates a new Hetzner Cloud server of last backup and updates DNS record'
inputs:
  TYPE_SERVER:
    description: 'Type of server'
    required: true
    default: 'cx11'
  NAME_SERVER:
    description: 'Name of server'
    required: true
    default: 'staging'
  HETZNER_PROJECT_TOKEN:
    description: 'Hetzner Cloud project token'
    required: true
  HETZNER_SSH_KEY_NAME:
    description: 'Hetzner Cloud SSH key name'
    default: ''
  HETZNER_DNS_ZONE:
    description: 'Hetzner Cloud DNS zone'
    required: true
  HETZNER_DNS_TOKEN:
    description: 'Hetzner Cloud DNS token'
    required: true
  HETZNER_FIREWALL_NAME:
    description: 'Hetzner Cloud firewall'
    required: true
  HETZNER_CLONE_SERVER:
    description: 'Hetzner Cloud server to clone'
    required: true
  HETZNER_CLOUD_COIFIG:
    description: 'Hetzner Cloud config file path for cloud-init'
    required: true


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.TYPE_SERVER }}
    - ${{ inputs.NAME_SERVER }}
    - ${{ inputs.HETZNER_PROJECT_TOKEN }}
    - ${{ inputs.HETZNER_SSH_KEY_NAME }}
    - ${{ inputs.HETZNER_DNS_ZONE }}
    - ${{ inputs.HETZNER_FIREWALL_NAME }}
    - ${{ inputs.HETZNER_DNS_TOKEN }}
    - ${{ inputs.HETZNER_CLONE_SERVER }}
    - ${{ inputs.HETZNER_CLOUD_COIFIG }}







